<a href="https://colab.research.google.com/github/Leonaxi/WhaleDataScienceProject/blob/master/Lecture_9_LSMC_with_3_periods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

discount = np.exp(-0.06)

# Regression at time 2
y = discount * np.array([0, 0.07, 0.18, 0.20, 0.09])
x = np.array([1.08, 1.07, .97, .77, .84])
X = np.column_stack([np.ones_like(x), x, x**2])
Θ2 = np.linalg.lstsq(X, y)[0]
print(Θ2)


[-1.06998766  2.98341063 -1.81357618]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


In [ ]:
def P2(S2):
  X = np.column_stack([np.ones_like(x), x, x**2])
  return X @ Θ2

S2 = np.array([1.08, 1.07, .97, .77, .84])


array([0.03674056, 0.04589834, 0.11752682, 0.15196921, 0.15641792])

In [ ]:
# For t = 1
r = 0.06
S1 = np.array([1.09, 0.93, .76, .92, .88])
X = np.column_stack([np.ones_like(S1), S1, S1**2])

y = np.array([0., 0.13, .33, .26, 0.]) * np.exp(-r)
Θ1 = np.linalg.lstsq(X, y)[0]

def P1(S1):
  # X = np.column_stack([np.ones_like(S1), S1, S1**2])
  # return X @  Θ1
  return Θ1[0] + Θ1[1] * S1+ Θ1[2] * S1**2

print(P1(S1))



[0.01348511 0.10874928 0.28606468 0.11700927 0.15276213]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys


In [ ]:
d = np.exp(-r)
DFC = np.array([0, 0, 0.07 * d, .17 * d**3, 0., .34 * d, 0.18 * d, 0.22 * d])

In [ ]:
P0 = np.mean(DFC)
print(P0)


0.11310315101789473
